services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CoopTilleuls\MigrationBundle\Tests\LegacyBundle\:
        resource: '%kernel.root_dir%/LegacyBundle/{Loader,Transformer}'
